osx_image: xcode10
language: objective-c

xcode_workspace: AxeWallet.xcworkspace
xcode_scheme: AxeWalletTests
xcode_destination: platform=iOS Simulator,OS=11.0,name=iPhone 6s
before_install:
- pod install
- set -o pipefail

script:
- fastlane test
